language: scala
scala:
  - 2.11.12
services:
  - docker
jdk:
  - oraclejdk8
node_js:
  - "8"
sudo: required
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/launchers
before_cache:
  # Ensure changes to the cache aren't persisted
  - rm -rf "$HOME/.ivy2/cache/com/lightbend/rp/reactivecli"
  # Delete all ivydata files since ivy touches them on each build
  - find "$HOME/.ivy2/cache" -name "ivydata-*.properties" -delete
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y jq
script:
  - sbt clean cliJS/test
    # We don't need to test/compile/package native here as buildAll will do that inside each Docker image
  - sbt clean update buildAll
